### ISSUE TITLE
Sorry! Accidently deleted a page from the wiki I think

### ISSUE THREAD

**Issue by sudhanshuraheja** [readmill/ios-wrapper#1]
Hi,

I was just trying things out and I think I managed to delete this page from your wiki - https://github.com/Readmill/ios-wrapper/wiki/Using-readmill-provided-ui

I'm really sorry because I didn't think that it would actually delete it. I just assumed I was seeing the delete page link by mistake.

I don't even have a backup, otherwise I would have put it back up.

Once again, I'm really sorry for this stupidity.

Regards,
Sudhanshu

**Comment by robb** [comment]
Reverted to the previous version, no worries.

**Comment by sudhanshuraheja** [comment]
Thanks.

On Sat, Mar 26, 2011 at 5:08 PM, robb <
reply@reply.github.com>wrote:

> Reverted to the previous version, no worries.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Readmill/ios-wrapper/issues/1#comment_920084

## 

Sudhanshu Raheja,
MD, Vercingetorix Technologies Pvt. Ltd. http://vxtindia.com
Phone : 0091-9960-980-066 | Skype : sudhanshu.raheja
